<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DocnetRuntime>win-x64</DocnetRuntime>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../THIRD-PARTY-NOTICES.md"
          Link="THIRD-PARTY-NOTICES.md"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
